Falco Dash Attack
chrispo-git/ult-s pull request #14
Opened 2022-09-17 14:59 UTC by mkPrieur

New falco dash attack based on vanilla fair

[Ultimate S Arcropolis.zip](https://github.com/chrispo-git/ult-s/files/9591968/Ultimate.S.Arcropolis.zip)

2022-09-19 21:38 UTC, mkPrieur commented
UPDATE:

[Ultimate S Arcropolis.zip](https://github.com/chrispo-git/ult-s/files/9602500/Ultimate.S.Arcropolis.zip)

2022-09-22 12:41 UTC, mkPrieur commented
UPDATED DOWNLOAD (plugin is above):

[Ultimate S Arcropolis.zip](https://github.com/chrispo-git/ult-s/files/9625781/Ultimate.S.Arcropolis.zip)

2022-09-22 14:23 UTC, chrispo-git requested changes
Okay so the dash attack multihits are generally fine but:
They can trip sometimes - change trip chance to -1.0
I'm ngl it proooobably shouldnt edge cancel like that, it looks kinda wack
probably increase startup back to frame 9 (have the motion rate start on frame 9 rather than 1)

2022-09-24 09:47 UTC, chrispo-git approved these changes

2022-10-02 19:50 UTC, closed without merging